### ISSUE TITLE
Problem with [ { } } w signs

### ISSUE THREAD

**Issue by sk0gen** [inkOfPixel/sms-length#2]
Why length for '[' is calculated as 2?

**Comment by federicobadini** [comment]
The `[` character is part of the extension set of the GSM7 alphabet, so it takes twice the space of a char included in the base character set.
Here is a reference: https://en.wikipedia.org/wiki/GSM_03.38

**Comment by sk0gen** [comment]
Yea. I stupidly wrote the issue. Sorry for inconvenience :)
